2024秋冬季rcore阶段二blog-殷金钰
rcore-os/blog pull request #549
Opened 2024-11-09 14:43 UTC by yjymosheng

完成了一二阶段的总结

2024-11-09 15:12 UTC, hky1999 requested changes

2024-11-09 15:12 UTC, hky1999 commented on package.json
> +    "version": "7.3.0"
revert your modification to this file

2024-11-09 15:12 UTC, hky1999 commented on package.json
> +}
revert it.

2024-11-10 02:18 UTC, yjymosheng commented
您好，已经修改了package.json的内容，麻烦您审核一下

2024-11-10 05:53 UTC, hky1999 approved these changes

2024-11-10 05:54 UTC, merged

2024-11-10 05:54 UTC, hky1999 commented
> 您好，已经修改了package.json的内容，麻烦您审核一下

merged, thanks