2024秋冬季开源操作系统训练营第二阶段总结-寒冰
rcore-os/blog pull request #620
Opened 2024-11-12 18:01 UTC by hanbings

2024-11-18 03:04 UTC, hky1999 approved these changes

2024-11-18 03:04 UTC, hky1999 requested changes
where is your blog for stage 1

2024-12-03 21:33 UTC, hanbings commented
> where is your blog for stage 1

Regarding the stage 1 report, I also participated in the training camp in the first half of this year and submitted the report at https://github.com/rcore-os/blog/commit/da6914362d23526873089057adaa1dd7631329f3.
I hope you don't mind, but I did not rewrite and resubmit the Stage 1 report, as the content has remained unchanged.

And because the PR has not been merged yet, I also submitted a stage 3 report.

Thanks for the review.

2024-12-22 09:15 UTC, hky1999 approved these changes

2024-12-22 09:15 UTC, merged

2024-12-22 09:16 UTC, hky1999 commented
> rticipated in the training camp in the first half of this year and submitted the report at [da69143](https://github.com/rcore-os/blog/commit/da6914362d23526873089057adaa1dd7631329f3). I hope you don't mind, but I did not rewrite and resubmit the Stage 1 report, as the content has remained unchanged.
> 
> And because the PR has not been merged yet, I also submitted a stage 3 report.
> 
> Thanks for the review.

got it

excellent work, keep going